# Generated by Django 5.1.4 on 2024-12-17 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_endereco_user_address_rename_nome_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.BinaryField()),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=20)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
