# Generated by Django 5.1.4 on 2024-12-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.TextField()),
                ('preferencias', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
