# Generated by Django 5.1.4 on 2024-12-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='preferencias',
            new_name='preferences',
        ),
    ]
