# Generated by Django 5.1.4 on 2025-01-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F'), ('unissex', 'U')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('finished', 'Finished')], max_length=50),
        ),
    ]
